sudo: false
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/aws_sdk_2.gemfile
  - gemfiles/aws_sdk_3.gemfile

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v 1.16.2

before_script:
  - docker-compose up -d

script: bundle exec rubocop --fail-level=C

after_script:
  - docker-compose down
