sudo: false
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - gemfiles/aws_sdk_3_rails_5.gemfile
  - gemfiles/aws_sdk_3_rails_6.gemfile

matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/aws_sdk_3_rails_6.gemfile

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v 1.16.2
  - gem update --system

before_script:
  - docker-compose up -d

script: bundle exec rubocop --fail-level=C

after_script:
  - docker-compose down
