sudo: false
language: ruby
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.2

before_script:
  - docker-compose up -d

script: bundle exec rubocop --fail-level=C

after_script:
  - docker-compose down
