version: '3'
services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
  dynamodb:
    image: cnadiminti/dynamodb-local:2019-02-07
    ports:
      - 8000:8000
