name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]
        gemfile: [ aws_sdk_2_rails_5, aws_sdk_2_rails_6, aws_sdk_3_rails_5, aws_sdk_3_rails_6 ]
        exclude:
        - { ruby: 2.4, gemfile: aws_sdk_2_rails_6 }
        - { ruby: 2.4, gemfile: aws_sdk_3_rails_6 }
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      TEST_DYNAMODB_ENDPOINT: 'http://0.0.0.0:8000'
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bin/setup
    - run: docker-compose up -d
    - run: docker ps
    - run: bundle exec rubocop --fail-level=C
    - run: bundle exec rake spec
    - run: docker-compose down
